const QUESTION_BANK = [
  {"category": "Geografia", "q": "Qual é a capital de Canadá?", "options": ["Toronto", "Vancouver", "Ottawa", "Montreal"], "answer": 2, "id": 1},
  {"category": "Geografia", "q": "Qual é a capital de Austrália?", "options": ["Sydney", "Melbourne", "Canberra", "Perth"], "answer": 2, "id": 2},
  {"category": "Geografia", "q": "Qual é a capital de Turquia?", "options": ["Istambul", "Ancara", "Esmirna", "Antália"], "answer": 1, "id": 3},
  {"category": "Geografia", "q": "Qual é a capital de Suíça?", "options": ["Zurique", "Genebra", "Berna", "Basileia"], "answer": 2, "id": 4},
  {"category": "Geografia", "q": "Qual é a capital de Nova Zelândia?", "options": ["Auckland", "Christchurch", "Wellington", "Hamilton"], "answer": 2, "id": 5},
  {"category": "Geografia", "q": "Qual é a capital de Marrocos?", "options": ["Casablanca", "Marrakech", "Rabat", "Fez"], "answer": 2, "id": 6},
  {"category": "Geografia", "q": "Qual é a capital de Nigéria?", "options": ["Lagos", "Kano", "Abuja", "Ibadan"], "answer": 2, "id": 7},
  {"category": "Geografia", "q": "Qual é a capital de Paquistão?", "options": ["Karachi", "Lahore", "Islamabad", "Peshawar"], "answer": 2, "id": 8},
  {"category": "Geografia", "q": "Qual é a capital de Cazaquistão?", "options": ["Almaty", "Astana", "Shymkent", "Karaganda"], "answer": 1, "id": 9},
  {"category": "Geografia", "q": "Qual é a capital de Mongólia?", "options": ["Ulan Bator", "Erdenet", "Darkhan", "Choibalsan"], "answer": 0, "id": 10},
  {"category": "Geografia", "q": "Qual é a capital de Croácia?", "options": ["Split", "Dubrovnik", "Zagreb", "Rijeka"], "answer": 2, "id": 11},
  {"category": "Geografia", "q": "Qual é a capital de Eslovênia?", "options": ["Maribor", "Liubliana", "Koper", "Celje"], "answer": 1, "id": 12},
  {"category": "Geografia", "q": "Qual é a capital de Eslováquia?", "options": ["Košice", "Bratislava", "Nitra", "Žilina"], "answer": 1, "id": 13},
  {"category": "Geografia", "q": "Qual é a capital de Lituânia?", "options": ["Kaunas", "Klaipėda", "Vilnius", "Šiauliai"], "answer": 2, "id": 14},
  {"category": "Geografia", "q": "Qual é a capital de Letônia?", "options": ["Riga", "Daugavpils", "Liepāja", "Jelgava"], "answer": 0, "id": 15},
  {"category": "Geografia", "q": "Qual é a capital de Estônia?", "options": ["Tartu", "Narva", "Tallinn", "Pärnu"], "answer": 2, "id": 16},
  {"category": "Geografia", "q": "Qual é a capital de Geórgia?", "options": ["Batumi", "Kutaisi", "Tbilisi", "Rustavi"], "answer": 2, "id": 17},
  {"category": "Geografia", "q": "Qual é a capital de Armênia?", "options": ["Gyumri", "Yerevan", "Vanadzor", "Goris"], "answer": 1, "id": 18},
  {"category": "Geografia", "q": "Qual é a capital de Azerbaijão?", "options": ["Ganja", "Baku", "Sumqayit", "Lankaran"], "answer": 1, "id": 19},
  {"category": "Geografia", "q": "Qual é a capital de Etiópia?", "options": ["Gondar", "Adis Abeba", "Dire Dawa", "Mekele"], "answer": 1, "id": 20},
  {"category": "Geografia", "q": "Qual é a capital de Quênia?", "options": ["Mombasa", "Nairóbi", "Kisumu", "Nakuru"], "answer": 1, "id": 21},
  {"category": "Geografia", "q": "Qual é a capital de Tanzânia?", "options": ["Dar es Salaam", "Arusha", "Dodoma", "Mwanza"], "answer": 2, "id": 22},
  {"category": "Geografia", "q": "Qual é a capital de Gana?", "options": ["Kumasi", "Tamale", "Acra", "Takoradi"], "answer": 2, "id": 23},
  {"category": "Geografia", "q": "Qual é a capital de Senegal?", "options": ["Saint-Louis", "Dacar", "Thiès", "Kaolack"], "answer": 1, "id": 24},
  {"category": "Geografia", "q": "Qual é a capital de Islândia?", "options": ["Akureyri", "Reykjavík", "Keflavík", "Selfoss"], "answer": 1, "id": 25},
  {"category": "Geografia", "q": "Qual é a capital de Noruega?", "options": ["Bergen", "Trondheim", "Oslo", "Stavanger"], "answer": 2, "id": 26},
  {"category": "Geografia", "q": "Qual é a capital de Finlândia?", "options": ["Turku", "Tampere", "Helsinque", "Oulu"], "answer": 2, "id": 27},
  {"category": "Geografia", "q": "Qual é a capital de Bulgária?", "options": ["Varna", "Plovdiv", "Sófia", "Burgas"], "answer": 2, "id": 28},
  {"category": "Geografia", "q": "Qual é a capital de Romênia?", "options": ["Cluj-Napoca", "Bucareste", "Timișoara", "Iași"], "answer": 1, "id": 29},
  {"category": "Geografia", "q": "Qual é a capital de Hungria?", "options": ["Debrecen", "Szeged", "Budapeste", "Pécs"], "answer": 2, "id": 30},
  {"category": "Geografia", "q": "Qual é a capital de Áustria?", "options": ["Salzburgo", "Graz", "Viena", "Innsbruck"], "answer": 2, "id": 31},
  {"category": "Geografia", "q": "Qual é a capital de Bélgica?", "options": ["Antuérpia", "Bruges", "Bruxelas", "Gante"], "answer": 2, "id": 32},
  {"category": "Geografia", "q": "Qual é a capital de Irlanda?", "options": ["Cork", "Galway", "Dublin", "Limerick"], "answer": 2, "id": 33},
  {"category": "Geografia", "q": "Qual é a capital de Portugal?", "options": ["Porto", "Coimbra", "Braga", "Lisboa"], "answer": 3, "id": 34},
  {"category": "Geografia", "q": "Qual é a capital de Peru?", "options": ["Cusco", "Arequipa", "Lima", "Trujillo"], "answer": 2, "id": 35},
  {"category": "História", "q": "Em que ano caiu o Muro de Berlim?", "options": ["1987", "1989", "1991", "1993"], "answer": 1, "id": 36},
  {"category": "História", "q": "Quem foi o primeiro imperador do Brasil?", "options": ["Dom Pedro I", "Dom Pedro II", "Dom João VI", "Deodoro da Fonseca"], "answer": 0, "id": 37},
  {"category": "História", "q": "A Revolução Francesa começou em qual ano?", "options": ["1776", "1789", "1804", "1815"], "answer": 1, "id": 38},
  {"category": "História", "q": "Qual civilização construiu Machu Picchu?", "options": ["Maia", "Asteca", "Inca", "Olmeca"], "answer": 2, "id": 39},
  {"category": "História", "q": "Quem liderou a expedição que chegou ao Brasil em 1500?", "options": ["Vasco da Gama", "Pedro Álvares Cabral", "Fernão de Magalhães", "Bartolomeu Dias"], "answer": 1, "id": 40},
  {"category": "História", "q": "Qual cidade romana foi soterrada pela erupção do Vesúvio em 79 d.C.?", "options": ["Pompeia", "Ravena", "Milão", "Verona"], "answer": 0, "id": 41},
  {"category": "História", "q": "A Magna Carta foi assinada em qual país?", "options": ["França", "Inglaterra", "Espanha", "Portugal"], "answer": 1, "id": 42},
  {"category": "História", "q": "Quem foi conhecido como o Rei Sol?", "options": ["Luís XIV", "Luís XVI", "Carlos Magno", "Napoleão"], "answer": 0, "id": 43},
  {"category": "História", "q": "Qual império tinha Constantinopla como capital?", "options": ["Bizantino", "Carolíngio", "Persa", "Mongol"], "answer": 0, "id": 44},
  {"category": "História", "q": "Em que ano terminou a Segunda Guerra Mundial?", "options": ["1943", "1944", "1945", "1946"], "answer": 2, "id": 45},
  {"category": "História", "q": "Qual navegador comandou a primeira circum-navegação iniciada em 1519?", "options": ["Cristóvão Colombo", "Fernão de Magalhães", "Américo Vespúcio", "James Cook"], "answer": 1, "id": 46},
  {"category": "História", "q": "Quem proclamou a República no Brasil em 1889?", "options": ["Floriano Peixoto", "Deodoro da Fonseca", "Prudente de Morais", "Benjamin Constant"], "answer": 1, "id": 47},
  {"category": "História", "q": "Qual foi a capital do Brasil imediatamente antes de Brasília?", "options": ["Salvador", "São Paulo", "Rio de Janeiro", "Belo Horizonte"], "answer": 2, "id": 48},
  {"category": "História", "q": "A independência dos Estados Unidos foi declarada em qual ano?", "options": ["1776", "1789", "1812", "1750"], "answer": 0, "id": 49},
  {"category": "História", "q": "Quem foi a rainha do Reino Unido durante grande parte do século XIX, dando nome a uma era?", "options": ["Elizabeth I", "Ana", "Vitória", "Maria II"], "answer": 2, "id": 50},
  {"category": "História", "q": "Qual povo antigo desenvolveu a democracia em Atenas?", "options": ["Romanos", "Gregos", "Fenícios", "Egípcios"], "answer": 1, "id": 51},
  {"category": "História", "q": "A Guerra dos Cem Anos envolveu principalmente quais países?", "options": ["França e Inglaterra", "Espanha e Portugal", "Prússia e Áustria", "Itália e França"], "answer": 0, "id": 52},
  {"category": "História", "q": "Quem escreveu as 95 Teses associadas ao início da Reforma Protestante?", "options": ["João Calvino", "Martinho Lutero", "Erasmo de Roterdã", "Thomas More"], "answer": 1, "id": 53},
  {"category": "História", "q": "Qual evento ocorreu em 14 de julho de 1789?", "options": ["Queda da Bastilha", "Batalha de Waterloo", "Congresso de Viena", "Golpe do 18 Brumário"], "answer": 0, "id": 54},
  {"category": "História", "q": "Qual dinastia governava a Rússia até a Revolução de 1917?", "options": ["Romanov", "Habsburgo", "Tudor", "Bourbon"], "answer": 0, "id": 55},
  {"category": "História", "q": "Qual tratado encerrou formalmente a Primeira Guerra Mundial com a Alemanha?", "options": ["Tratado de Tordesilhas", "Tratado de Versalhes", "Tratado de Utrecht", "Tratado de Paris"], "answer": 1, "id": 56},
  {"category": "História", "q": "Quem foi o líder sul-africano eleito presidente em 1994 após o apartheid?", "options": ["Nelson Mandela", "Desmond Tutu", "Thabo Mbeki", "F. W. de Klerk"], "answer": 0, "id": 57},
  {"category": "História", "q": "Qual cidade foi a primeira capital do Brasil colonial?", "options": ["Rio de Janeiro", "Recife", "Salvador", "Olinda"], "answer": 2, "id": 58},
  {"category": "História", "q": "Em que século ocorreu a chegada de Cabral ao Brasil?", "options": ["XIV", "XV", "XVI", "XVII"], "answer": 2, "id": 59},
  {"category": "História", "q": "Qual país lançou o primeiro satélite artificial, Sputnik 1?", "options": ["Estados Unidos", "União Soviética", "China", "França"], "answer": 1, "id": 60},
  {"category": "Ciência", "q": "Qual é o símbolo químico do ouro?", "options": ["Ag", "Au", "O", "Fe"], "answer": 1, "id": 61},
  {"category": "Ciência", "q": "Qual elemento tem número atômico 1?", "options": ["Hélio", "Hidrogênio", "Oxigênio", "Carbono"], "answer": 1, "id": 62},
  {"category": "Ciência", "q": "Qual é o maior planeta do Sistema Solar?", "options": ["Saturno", "Júpiter", "Netuno", "Terra"], "answer": 1, "id": 63},
  {"category": "Ciência", "q": "Qual órgão humano produz insulina?", "options": ["Fígado", "Pâncreas", "Rim", "Baço"], "answer": 1, "id": 64},
  {"category": "Ciência", "q": "Qual gás é mais abundante na atmosfera terrestre?", "options": ["Oxigênio", "Nitrogênio", "Argônio", "Dióxido de carbono"], "answer": 1, "id": 65},
  {"category": "Ciência", "q": "Qual é a unidade SI de força?", "options": ["Joule", "Watt", "Newton", "Pascal"], "answer": 2, "id": 66},
  {"category": "Ciência", "q": "Quantos cromossomos há normalmente em uma célula somática humana?", "options": ["23", "44", "46", "48"], "answer": 2, "id": 67},
  {"category": "Ciência", "q": "Qual partícula subatômica possui carga negativa?", "options": ["Próton", "Nêutron", "Elétron", "Fóton"], "answer": 2, "id": 68},
  {"category": "Ciência", "q": "Qual planeta possui o dia mais longo do Sistema Solar em duração de rotação?", "options": ["Mercúrio", "Vênus", "Marte", "Saturno"], "answer": 1, "id": 69},
  {"category": "Ciência", "q": "Qual vitamina é produzida na pele com auxílio da luz solar?", "options": ["A", "C", "D", "K"], "answer": 2, "id": 70},
  {"category": "Ciência", "q": "Qual é a fórmula química da água?", "options": ["CO2", "H2O", "O2", "H2O2"], "answer": 1, "id": 71},
  {"category": "Ciência", "q": "Quem formulou as leis clássicas do movimento e da gravitação universal?", "options": ["Einstein", "Newton", "Galileu", "Kepler"], "answer": 1, "id": 72},
  {"category": "Ciência", "q": "Qual escala mede a acidez ou alcalinidade de uma solução?", "options": ["Richter", "pH", "Kelvin", "Beaufort"], "answer": 1, "id": 73},
  {"category": "Ciência", "q": "Qual metal é líquido em condições ambientes usuais?", "options": ["Mercúrio", "Alumínio", "Cobre", "Ferro"], "answer": 0, "id": 74},
  {"category": "Ciência", "q": "Qual é a camada mais externa sólida da Terra?", "options": ["Núcleo", "Manto", "Crosta", "Astenosfera"], "answer": 2, "id": 75},
  {"category": "Ciência", "q": "Como se chama o processo pelo qual plantas convertem luz em energia química?", "options": ["Respiração", "Fotossíntese", "Fermentação", "Osmose"], "answer": 1, "id": 76},
  {"category": "Ciência", "q": "Qual é a velocidade aproximada da luz no vácuo?", "options": ["30 mil km/s", "300 mil km/s", "3 mil km/s", "3 milhões km/s"], "answer": 1, "id": 77},
  {"category": "Ciência", "q": "Qual cientista propôs a teoria da evolução por seleção natural?", "options": ["Darwin", "Mendel", "Pasteur", "Bohr"], "answer": 0, "id": 78},
  {"category": "Ciência", "q": "Qual é o maior osso do corpo humano?", "options": ["Tíbia", "Úmero", "Fêmur", "Fíbula"], "answer": 2, "id": 79},
  {"category": "Ciência", "q": "Qual parte do átomo concentra prótons e nêutrons?", "options": ["Eletrosfera", "Núcleo", "Orbital", "Íon"], "answer": 1, "id": 80},
  {"category": "Ciência", "q": "Qual planeta é famoso por seus anéis mais visíveis?", "options": ["Marte", "Saturno", "Urano", "Netuno"], "answer": 1, "id": 81},
  {"category": "Ciência", "q": "Qual é a unidade SI de corrente elétrica?", "options": ["Volt", "Ampere", "Ohm", "Watt"], "answer": 1, "id": 82},
  {"category": "Ciência", "q": "Qual grupo sanguíneo é conhecido como doador universal de hemácias, considerando ABO e Rh?", "options": ["AB+", "O-", "A-", "O+"], "answer": 1, "id": 83},
  {"category": "Ciência", "q": "Qual gás as plantas absorvem principalmente para a fotossíntese?", "options": ["Oxigênio", "Nitrogênio", "Dióxido de carbono", "Hidrogênio"], "answer": 2, "id": 84},
  {"category": "Ciência", "q": "Qual estrutura celular contém a maior parte do DNA em células eucarióticas?", "options": ["Ribossomo", "Núcleo", "Lisossomo", "Complexo de Golgi"], "answer": 1, "id": 85},
  {"category": "Ciência", "q": "Qual é o nome da passagem direta do estado sólido para o gasoso?", "options": ["Fusão", "Sublimação", "Condensação", "Vaporização"], "answer": 1, "id": 86},
  {"category": "Ciência", "q": "Qual instrumento mede a pressão atmosférica?", "options": ["Higrômetro", "Barômetro", "Anemômetro", "Calorímetro"], "answer": 1, "id": 87},
  {"category": "Ciência", "q": "Qual cientista desenvolveu a teoria da relatividade?", "options": ["Niels Bohr", "Albert Einstein", "Max Planck", "Michael Faraday"], "answer": 1, "id": 88},
  {"category": "Ciência", "q": "Qual é o pH aproximado de uma solução neutra a 25 °C?", "options": ["0", "5", "7", "14"], "answer": 2, "id": 89},
  {"category": "Ciência", "q": "Qual órgão é responsável principalmente pelas trocas gasosas no corpo humano?", "options": ["Coração", "Pulmões", "Fígado", "Rins"], "answer": 1, "id": 90},
  {"category": "Cinema, Música & Artes", "q": "Quem pintou \"Guernica\"?", "options": ["Salvador Dalí", "Pablo Picasso", "Joan Miró", "Claude Monet"], "answer": 1, "id": 91},
  {"category": "Cinema, Música & Artes", "q": "Quem escreveu \"1984\"?", "options": ["George Orwell", "Aldous Huxley", "Ray Bradbury", "J. D. Salinger"], "answer": 0, "id": 92},
  {"category": "Cinema, Música & Artes", "q": "Quem compôs \"As Quatro Estações\"?", "options": ["Mozart", "Bach", "Vivaldi", "Beethoven"], "answer": 2, "id": 93},
  {"category": "Cinema, Música & Artes", "q": "Qual diretor comandou o filme \"Tubarão\" (1975)?", "options": ["George Lucas", "Steven Spielberg", "Francis Ford Coppola", "Martin Scorsese"], "answer": 1, "id": 94},
  {"category": "Cinema, Música & Artes", "q": "Em \"O Senhor dos Anéis\", qual é o nome do portador do Um Anel na jornada principal?", "options": ["Aragorn", "Frodo", "Gandalf", "Legolas"], "answer": 1, "id": 95},
  {"category": "Cinema, Música & Artes", "q": "Qual banda lançou o álbum \"The Dark Side of the Moon\"?", "options": ["Queen", "Pink Floyd", "Led Zeppelin", "The Who"], "answer": 1, "id": 96},
  {"category": "Cinema, Música & Artes", "q": "Quem escreveu \"Dom Quixote\"?", "options": ["Miguel de Cervantes", "Federico García Lorca", "Gabriel García Márquez", "Jorge Luis Borges"], "answer": 0, "id": 97},
  {"category": "Cinema, Música & Artes", "q": "Qual atriz interpretou Hermione Granger nos filmes de Harry Potter?", "options": ["Emma Stone", "Emma Watson", "Keira Knightley", "Natalie Portman"], "answer": 1, "id": 98},
  {"category": "Cinema, Música & Artes", "q": "Qual artista pintou \"A Noite Estrelada\"?", "options": ["Van Gogh", "Monet", "Renoir", "Cézanne"], "answer": 0, "id": 99},
  {"category": "Cinema, Música & Artes", "q": "Qual personagem é o alter ego de Bruce Wayne?", "options": ["Superman", "Batman", "Flash", "Aquaman"], "answer": 1, "id": 100},
  {"category": "Cinema, Música & Artes", "q": "Quem escreveu \"O Pequeno Príncipe\"?", "options": ["Victor Hugo", "Antoine de Saint-Exupéry", "Jules Verne", "Albert Camus"], "answer": 1, "id": 101},
  {"category": "Cinema, Música & Artes", "q": "Qual banda tinha Freddie Mercury como vocalista?", "options": ["Queen", "Kiss", "Aerosmith", "The Police"], "answer": 0, "id": 102},
  {"category": "Cinema, Música & Artes", "q": "Qual filme venceu o Oscar de Melhor Filme na cerimônia de 1998, referente aos filmes de 1997?", "options": ["Titanic", "Los Angeles: Cidade Proibida", "Gênio Indomável", "Ou Tudo ou Nada"], "answer": 0, "id": 103},
  {"category": "Cinema, Música & Artes", "q": "Quem criou o personagem Sherlock Holmes?", "options": ["Agatha Christie", "Arthur Conan Doyle", "Edgar Allan Poe", "G. K. Chesterton"], "answer": 1, "id": 104},
  {"category": "Cinema, Música & Artes", "q": "Qual instrumento tem tradicionalmente 88 teclas?", "options": ["Piano", "Acordeão", "Cravo", "Órgão"], "answer": 0, "id": 105},
  {"category": "Cinema, Música & Artes", "q": "Qual cantor ficou conhecido como \"Rei do Pop\"?", "options": ["Prince", "Michael Jackson", "Elvis Presley", "Stevie Wonder"], "answer": 1, "id": 106},
  {"category": "Cinema, Música & Artes", "q": "Quem dirigiu \"Pulp Fiction\"?", "options": ["Quentin Tarantino", "David Fincher", "Ridley Scott", "Tim Burton"], "answer": 0, "id": 107},
  {"category": "Cinema, Música & Artes", "q": "Qual romance começa com a família Buendía em Macondo?", "options": ["Cem Anos de Solidão", "O Amor nos Tempos do Cólera", "Pedro Páramo", "A Casa dos Espíritos"], "answer": 0, "id": 108},
  {"category": "Cinema, Música & Artes", "q": "Qual banda britânica gravou \"Bohemian Rhapsody\"?", "options": ["The Beatles", "Queen", "Oasis", "Muse"], "answer": 1, "id": 109},
  {"category": "Cinema, Música & Artes", "q": "Qual personagem da Disney perde um sapatinho de cristal?", "options": ["Aurora", "Cinderela", "Bela", "Ariel"], "answer": 1, "id": 110},
  {"category": "Cinema, Música & Artes", "q": "Quem pintou o teto da Capela Sistina?", "options": ["Leonardo da Vinci", "Michelangelo", "Rafael", "Donatello"], "answer": 1, "id": 111},
  {"category": "Cinema, Música & Artes", "q": "Qual escritor brasileiro criou Capitu e Bentinho?", "options": ["Machado de Assis", "José de Alencar", "Graciliano Ramos", "Jorge Amado"], "answer": 0, "id": 112},
  {"category": "Cinema, Música & Artes", "q": "Qual série apresenta as casas Stark e Lannister?", "options": ["Vikings", "Game of Thrones", "The Witcher", "The Last Kingdom"], "answer": 1, "id": 113},
  {"category": "Cinema, Música & Artes", "q": "Qual cineasta dirigiu \"O Poderoso Chefão\"?", "options": ["Francis Ford Coppola", "Brian De Palma", "Stanley Kubrick", "Sergio Leone"], "answer": 0, "id": 114},
  {"category": "Cinema, Música & Artes", "q": "Qual artista lançou o álbum \"Thriller\"?", "options": ["Prince", "Michael Jackson", "Lionel Richie", "Stevie Wonder"], "answer": 1, "id": 115},
  {"category": "Cinema, Música & Artes", "q": "Quem escreveu \"A Metamorfose\"?", "options": ["Franz Kafka", "Thomas Mann", "Hermann Hesse", "Bertolt Brecht"], "answer": 0, "id": 116},
  {"category": "Cinema, Música & Artes", "q": "Qual movimento artístico é fortemente associado a Salvador Dalí?", "options": ["Cubismo", "Surrealismo", "Impressionismo", "Fauvismo"], "answer": 1, "id": 117},
  {"category": "Cinema, Música & Artes", "q": "Qual atriz interpretou a protagonista de \"A Professora de Piano\", de Michael Haneke?", "options": ["Juliette Binoche", "Isabelle Huppert", "Emmanuelle Béart", "Sophie Marceau"], "answer": 1, "id": 118},
  {"category": "Cinema, Música & Artes", "q": "Qual diretor criou \"2001: Uma Odisseia no Espaço\"?", "options": ["Stanley Kubrick", "Alfred Hitchcock", "Orson Welles", "David Lean"], "answer": 0, "id": 119},
  {"category": "Cinema, Música & Artes", "q": "Qual escritor é autor de \"O Nome da Rosa\"?", "options": ["Italo Calvino", "Umberto Eco", "Primo Levi", "Alberto Moravia"], "answer": 1, "id": 120},
  {"category": "Esportes", "q": "No tênis, como se chama o placar de 40 a 40?", "options": ["Set point", "Deuce", "Tie-break", "Love"], "answer": 1, "id": 121},
  {"category": "Esportes", "q": "Quantos pontos vale um touchdown no futebol americano antes do ponto extra?", "options": ["3", "6", "7", "8"], "answer": 1, "id": 122},
  {"category": "Esportes", "q": "Em qual esporte é disputada a Stanley Cup?", "options": ["Basquete", "Hóquei no gelo", "Beisebol", "Rugby"], "answer": 1, "id": 123},
  {"category": "Esportes", "q": "Qual país venceu a primeira Copa do Mundo de futebol, em 1930?", "options": ["Brasil", "Argentina", "Uruguai", "Itália"], "answer": 2, "id": 124},
  {"category": "Esportes", "q": "Quantos jogadores de uma equipe de vôlei ficam em quadra?", "options": ["5", "6", "7", "8"], "answer": 1, "id": 125},
  {"category": "Esportes", "q": "Qual é a distância oficial de uma maratona?", "options": ["40 km", "41,195 km", "42,195 km", "43 km"], "answer": 2, "id": 126},
  {"category": "Esportes", "q": "Em qual esporte se usa o termo \"birdie\"?", "options": ["Golfe", "Tênis", "Críquete", "Badminton"], "answer": 0, "id": 127},
  {"category": "Esportes", "q": "Quantos anéis há no símbolo olímpico?", "options": ["4", "5", "6", "7"], "answer": 1, "id": 128},
  {"category": "Esportes", "q": "Qual piloto brasileiro foi tricampeão mundial de Fórmula 1?", "options": ["Emerson Fittipaldi", "Nelson Piquet", "Ayrton Senna", "Rubens Barrichello"], "answer": 2, "id": 129},
  {"category": "Esportes", "q": "No basquete, quantos pontos vale uma cesta feita além da linha de três?", "options": ["2", "3", "4", "5"], "answer": 1, "id": 130},
  {"category": "Esportes", "q": "Qual país é associado à origem do judô?", "options": ["China", "Japão", "Coreia do Sul", "Tailândia"], "answer": 1, "id": 131},
  {"category": "Esportes", "q": "Em qual modalidade se usa florete, espada e sabre?", "options": ["Esgrima", "Pentatlo", "Tiro esportivo", "Ginástica"], "answer": 0, "id": 132},
  {"category": "Esportes", "q": "Quantos buracos tem uma volta padrão de golfe?", "options": ["9", "12", "18", "24"], "answer": 2, "id": 133},
  {"category": "Esportes", "q": "Qual seleção masculina de futebol ganhou a Copa do Mundo de 2010?", "options": ["Alemanha", "Espanha", "Holanda", "Itália"], "answer": 1, "id": 134},
  {"category": "Esportes", "q": "Em qual esporte atua um quarterback?", "options": ["Rugby", "Futebol americano", "Beisebol", "Hóquei"], "answer": 1, "id": 135},
  {"category": "Esportes", "q": "Qual torneio de tênis é disputado tradicionalmente na grama?", "options": ["Roland Garros", "US Open", "Wimbledon", "Australian Open"], "answer": 2, "id": 136},
  {"category": "Esportes", "q": "Quantos jogadores cada time tem em campo no futebol, incluindo o goleiro?", "options": ["10", "11", "12", "9"], "answer": 1, "id": 137},
  {"category": "Esportes", "q": "Qual peça vale mais pontos no xadrez, desconsiderando o rei?", "options": ["Torre", "Bispo", "Rainha", "Cavalo"], "answer": 2, "id": 138},
  {"category": "Esportes", "q": "Em qual país nasceu o futebolista Lionel Messi?", "options": ["Espanha", "Argentina", "Uruguai", "Chile"], "answer": 1, "id": 139},
  {"category": "Esportes", "q": "Qual esporte utiliza uma peteca e raquetes?", "options": ["Squash", "Badminton", "Tênis de mesa", "Padel"], "answer": 1, "id": 140},
  {"category": "Esportes", "q": "Na Fórmula 1, qual bandeira indica o fim da corrida?", "options": ["Amarela", "Vermelha", "Quadriculada", "Azul"], "answer": 2, "id": 141},
  {"category": "Esportes", "q": "Qual seleção venceu a Copa do Mundo masculina de 2002?", "options": ["Brasil", "Alemanha", "França", "Itália"], "answer": 0, "id": 142},
  {"category": "Esportes", "q": "Qual é a pontuação máxima possível com três dardos no alvo padrão?", "options": ["150", "160", "180", "200"], "answer": 2, "id": 143},
  {"category": "Esportes", "q": "Em qual esporte há posições chamadas pitcher e catcher?", "options": ["Beisebol", "Basquete", "Críquete", "Handebol"], "answer": 0, "id": 144},
  {"category": "Esportes", "q": "Qual país sediou os Jogos Olímpicos de 2016?", "options": ["China", "Brasil", "Reino Unido", "Japão"], "answer": 1, "id": 145},
  {"category": "Brasil", "q": "Qual é o maior estado brasileiro em área?", "options": ["Pará", "Amazonas", "Mato Grosso", "Minas Gerais"], "answer": 1, "id": 146},
  {"category": "Brasil", "q": "Qual é a capital de Santa Catarina?", "options": ["Joinville", "Florianópolis", "Blumenau", "Chapecó"], "answer": 1, "id": 147},
  {"category": "Brasil", "q": "Qual bioma ocupa grande parte da Região Norte do Brasil?", "options": ["Cerrado", "Amazônia", "Caatinga", "Pampa"], "answer": 1, "id": 148},
  {"category": "Brasil", "q": "Qual escritor criou a personagem Emília do Sítio do Picapau Amarelo?", "options": ["Monteiro Lobato", "Carlos Drummond", "Érico Veríssimo", "Lima Barreto"], "answer": 0, "id": 149},
  {"category": "Brasil", "q": "Qual cidade é conhecida como a capital federal do Brasil desde 1960?", "options": ["Rio de Janeiro", "Brasília", "Salvador", "Goiânia"], "answer": 1, "id": 150},
  {"category": "Brasil", "q": "Qual é a capital do Pará?", "options": ["Belém", "Santarém", "Macapá", "Manaus"], "answer": 0, "id": 151},
  {"category": "Brasil", "q": "Qual estado brasileiro tem Porto Alegre como capital?", "options": ["Santa Catarina", "Paraná", "Rio Grande do Sul", "Mato Grosso do Sul"], "answer": 2, "id": 152},
  {"category": "Brasil", "q": "Qual arquiteto projetou importantes edifícios de Brasília, como o Congresso Nacional?", "options": ["Lúcio Costa", "Oscar Niemeyer", "Burle Marx", "Paulo Mendes da Rocha"], "answer": 1, "id": 153},
  {"category": "Brasil", "q": "Qual rio é associado às Cataratas do Iguaçu?", "options": ["Paraná", "Iguaçu", "Uruguai", "Tietê"], "answer": 1, "id": 154},
  {"category": "Brasil", "q": "Qual é a capital de Pernambuco?", "options": ["Olinda", "Recife", "Caruaru", "Petrolina"], "answer": 1, "id": 155},
  {"category": "Brasil", "q": "Qual movimento artístico brasileiro teve como marco a Semana de Arte Moderna de 1922?", "options": ["Barroco", "Modernismo", "Arcadismo", "Parnasianismo"], "answer": 1, "id": 156},
  {"category": "Brasil", "q": "Em qual cidade ocorreu a Semana de Arte Moderna de 1922?", "options": ["Rio de Janeiro", "São Paulo", "Belo Horizonte", "Salvador"], "answer": 1, "id": 157},
  {"category": "Brasil", "q": "Qual é a capital do Ceará?", "options": ["Fortaleza", "Juazeiro do Norte", "Sobral", "Crato"], "answer": 0, "id": 158},
  {"category": "Brasil", "q": "Qual estado brasileiro possui a ilha de Marajó?", "options": ["Amapá", "Pará", "Maranhão", "Amazonas"], "answer": 1, "id": 159},
  {"category": "Brasil", "q": "Quem escreveu \"Grande Sertão: Veredas\"?", "options": ["João Guimarães Rosa", "Jorge Amado", "Clarice Lispector", "João Cabral de Melo Neto"], "answer": 0, "id": 160},
  {"category": "Brasil", "q": "Qual é a capital de Mato Grosso?", "options": ["Campo Grande", "Cuiabá", "Goiânia", "Rondonópolis"], "answer": 1, "id": 161},
  {"category": "Brasil", "q": "Qual cidade brasileira é famosa pelo Elevador Lacerda?", "options": ["Recife", "Salvador", "Vitória", "Fortaleza"], "answer": 1, "id": 162},
  {"category": "Brasil", "q": "Qual estado tem Vitória como capital?", "options": ["Espírito Santo", "Bahia", "Sergipe", "Alagoas"], "answer": 0, "id": 163},
  {"category": "Brasil", "q": "Qual é a capital do Maranhão?", "options": ["São Luís", "Teresina", "Imperatriz", "Parnaíba"], "answer": 0, "id": 164},
  {"category": "Brasil", "q": "Qual compositor brasileiro escreveu \"Aquarela do Brasil\"?", "options": ["Ary Barroso", "Tom Jobim", "Noel Rosa", "Pixinguinha"], "answer": 0, "id": 165},
  {"category": "Brasil", "q": "Qual é a capital de Goiás?", "options": ["Anápolis", "Goiânia", "Brasília", "Aparecida de Goiânia"], "answer": 1, "id": 166},
  {"category": "Brasil", "q": "Qual estado brasileiro tem Palmas como capital?", "options": ["Tocantins", "Rondônia", "Roraima", "Acre"], "answer": 0, "id": 167},
  {"category": "Brasil", "q": "Qual é a capital do Rio Grande do Norte?", "options": ["Mossoró", "Natal", "João Pessoa", "Campina Grande"], "answer": 1, "id": 168},
  {"category": "Brasil", "q": "Quem escreveu \"Vidas Secas\"?", "options": ["Graciliano Ramos", "Jorge Amado", "José Lins do Rego", "Rachel de Queiroz"], "answer": 0, "id": 169},
  {"category": "Brasil", "q": "Qual é a capital do Acre?", "options": ["Cruzeiro do Sul", "Rio Branco", "Porto Velho", "Boa Vista"], "answer": 1, "id": 170},
  {"category": "Gastronomia & Bar", "q": "Qual destilado é a base clássica de um Negroni?", "options": ["Vodka", "Gin", "Rum", "Tequila"], "answer": 1, "id": 171},
  {"category": "Gastronomia & Bar", "q": "Qual ingrediente dá a cor e sabor característicos ao risoto alla milanese?", "options": ["Páprica", "Açafrão", "Cúrcuma", "Urucum"], "answer": 1, "id": 172},
  {"category": "Gastronomia & Bar", "q": "Qual queijo é tradicionalmente usado no tiramisù?", "options": ["Ricota", "Mascarpone", "Gorgonzola", "Brie"], "answer": 1, "id": 173},
  {"category": "Gastronomia & Bar", "q": "Qual destilado é usado no mojito clássico?", "options": ["Rum", "Gin", "Vodka", "Bourbon"], "answer": 0, "id": 174},
  {"category": "Gastronomia & Bar", "q": "Qual é o principal ingrediente do guacamole?", "options": ["Abacate", "Pepino", "Tomate", "Pimentão"], "answer": 0, "id": 175},
  {"category": "Gastronomia & Bar", "q": "Qual bebida é tradicionalmente usada em um Aperol Spritz além de Aperol e água com gás?", "options": ["Prosecco", "Vinho tinto", "Cerveja", "Saquê"], "answer": 0, "id": 176},
  {"category": "Gastronomia & Bar", "q": "De qual grão é feito tradicionalmente o tofu?", "options": ["Grão-de-bico", "Soja", "Lentilha", "Arroz"], "answer": 1, "id": 177},
  {"category": "Gastronomia & Bar", "q": "Qual massa italiana tem formato de pequenos grãos semelhantes a arroz?", "options": ["Orzo", "Penne", "Fusilli", "Rigatoni"], "answer": 0, "id": 178},
  {"category": "Gastronomia & Bar", "q": "Qual ingrediente é essencial no molho pesto genovês tradicional?", "options": ["Manjericão", "Salsa", "Coentro", "Alecrim"], "answer": 0, "id": 179},
  {"category": "Gastronomia & Bar", "q": "Qual destilado compõe a base de uma Margarita clássica?", "options": ["Tequila", "Rum", "Gin", "Cachaça"], "answer": 0, "id": 180},
  {"category": "Gastronomia & Bar", "q": "Qual estilo de cerveja alemã é tradicionalmente associado a Munique e à Oktoberfest histórica moderna?", "options": ["Märzen", "Stout", "Porter", "Saison"], "answer": 0, "id": 181},
  {"category": "Gastronomia & Bar", "q": "Qual ingrediente fermentado é a base do missô japonês mais comum?", "options": ["Soja", "Milho", "Batata", "Mandioca"], "answer": 0, "id": 182},
  {"category": "Gastronomia & Bar", "q": "Qual é o destilado base de uma Caipirinha tradicional?", "options": ["Cachaça", "Vodka", "Rum", "Gin"], "answer": 0, "id": 183},
  {"category": "Gastronomia & Bar", "q": "Qual coquetel clássico leva whisky, açúcar, bitters e casca de laranja?", "options": ["Old Fashioned", "Daiquiri", "Gimlet", "Moscow Mule"], "answer": 0, "id": 184},
  {"category": "Gastronomia & Bar", "q": "Qual vinho fortificado é tradicionalmente usado no Dry Martini em pequena proporção?", "options": ["Vermute seco", "Porto", "Jerez doce", "Marsala"], "answer": 0, "id": 185},
  {"category": "Tecnologia & Gerais", "q": "O que significa a sigla CPU?", "options": ["Central Processing Unit", "Computer Personal Utility", "Core Program User", "Central Power Utility"], "answer": 0, "id": 186},
  {"category": "Tecnologia & Gerais", "q": "Quem é creditado como criador da World Wide Web?", "options": ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Vint Cerf"], "answer": 1, "id": 187},
  {"category": "Tecnologia & Gerais", "q": "Em computação, quantos bits formam um byte?", "options": ["4", "8", "16", "32"], "answer": 1, "id": 188},
  {"category": "Tecnologia & Gerais", "q": "Qual linguagem é usada principalmente para estruturar conteúdo de páginas web?", "options": ["HTML", "SQL", "Python", "C++"], "answer": 0, "id": 189},
  {"category": "Tecnologia & Gerais", "q": "Qual empresa desenvolveu originalmente o sistema operacional Android?", "options": ["Android Inc., depois adquirida pelo Google", "Microsoft", "Nokia", "IBM"], "answer": 0, "id": 190},
  {"category": "Tecnologia & Gerais", "q": "O protocolo HTTPS adiciona principalmente o quê ao HTTP?", "options": ["Criptografia da comunicação", "Mais velocidade de CPU", "Compressão de imagens", "Armazenamento local"], "answer": 0, "id": 191},
  {"category": "Tecnologia & Gerais", "q": "Qual unidade equivale a 1.000 metros?", "options": ["Centímetro", "Quilômetro", "Milímetro", "Hectômetro"], "answer": 1, "id": 192},
  {"category": "Tecnologia & Gerais", "q": "Quantos lados tem um dodecágono?", "options": ["10", "11", "12", "14"], "answer": 2, "id": 193},
  {"category": "Tecnologia & Gerais", "q": "Qual número romano representa 50?", "options": ["L", "C", "D", "X"], "answer": 0, "id": 194},
  {"category": "Tecnologia & Gerais", "q": "Qual é a raiz quadrada de 144?", "options": ["10", "11", "12", "14"], "answer": 2, "id": 195},
  {"category": "Tecnologia & Gerais", "q": "Qual idioma tem o maior número de falantes nativos no mundo?", "options": ["Inglês", "Mandarim", "Espanhol", "Hindi"], "answer": 1, "id": 196},
  {"category": "Tecnologia & Gerais", "q": "Qual moeda é usada oficialmente no Japão?", "options": ["Won", "Yuan", "Iene", "Baht"], "answer": 2, "id": 197},
  {"category": "Tecnologia & Gerais", "q": "Quantos minutos há em 2 horas e meia?", "options": ["120", "130", "150", "180"], "answer": 2, "id": 198},
  {"category": "Tecnologia & Gerais", "q": "Qual é o menor número primo?", "options": ["0", "1", "2", "3"], "answer": 2, "id": 199},
  {"category": "Tecnologia & Gerais", "q": "Em um baralho padrão sem coringas, quantas cartas existem?", "options": ["48", "50", "52", "54"], "answer": 2, "id": 200}
];
